ray_local_mode: False
num_cpus:       24
num_gpus:       0
method:         QuantumKernels
ray_logging_path: logs/make_class
ray_num_trial_samples:  10
type:                   train

algorithm_config:
  dataset:          corners
  num_samples:      100
  num_features:     2
  feature_scaling:  none
  full_kta:         False
  cost_function:    trace_kta
  subsample_size:   8
  lr:               0.1
  num_epochs:       1000
  num_layers:       5
  num_qubits_equal_num_features:  False
  num_batches_per_epoch: 1
  use_importance_sampling:  False
  ansatz:           paper
  num_qubits:       4
  use_input_scaling:  True
  use_data_reuploading: True
  use_nystrom_approx:     True
  num_landmarks:          #1
    - grid_search
    - int
    - [1,2,4,8]
  validate_every_epoch:  25

  use_shots:    False
  n_shots:      100

  use_coherent_noise:     True
  std:                    #0
    - grid_search
    - float
    - [0.1,0.2,0.5]
  
  use_depolarizing_noise:     False
  depolarizing_strength:      0.01
  
  # 1440 * 3 runs


